### ISSUE TITLE
Check graphics driver with D3D API

### ISSUE THREAD

**Issue by elsamuko** [CheckPointSW/Evasions#6]
See https://gist.github.com/elsamuko/d3049d52ca235112c99ac3ee30282846

PS:
cppsh can be downloaded here: https://github.com/elsamuko/cppsh

**Comment by chkp-alexanderc** [comment]
Thanks for the interesting technique. We would assess it and include in the encyclopedia if applicable.

**Comment by chkp-alexanderc** [comment]
@elsamuko The technique has been added https://evasions.checkpoint.com/techniques/hardware.html#check-directx-adapter. Thank you.
