### ISSUE TITLE
1. Check vendor ID string via CPUID instruction ?

### ISSUE THREAD

**Issue by footballs** [CheckPointSW/Evasions#8]
I read many awesome articles from  evasion.checkpoint.com and very impressed !
I also came here from it.

https://github.com/CheckPointSW/Evasions/blob/master/_techniques/cpu.md#1-check-vendor-id-string-via-cpuid-instruction

I want to test it. How do you call this function ? 
It looks interesting to detect most popular VMs.

**Comment by footballs** [comment]
Sorry, please see 
https://github.com/CheckPointSW/InviZzzible/issues/11
Close it after seeing. Thanks

**Comment by chkp-alexanderc** [comment]
Hi @footballs,

There is a code sample provided in the repo.

Closed.

**Comment by footballs** [comment]
I know but how to call that code sample function  ?
```cpp
  try {
    char cpuid_[sizeof(DWORD) * 3 + 1] = {};
    //get_cpu_vendor_id(cpuid_);
    get_cpuid_vendor(cpuid_);
    cout << cpuid_;
  } catch (exception & e) {
    cout << "Standard exception: " << e.what() << endl;
  }
  return 0;
```

**Result:**
![Capture](https://user-images.githubusercontent.com/70466231/99393152-bc3f4780-28fe-11eb-835a-964f91331a15.PNG)
